<?php

declare(strict_types=1);

namespace Lunar\Entity;

/**
 * Énumération des sources possibles pour les images.
 *
 * Chaque source a ses propres caractéristiques :
 * - UPLOAD : Image uploadée par l'utilisateur
 * - PEXELS : Image libre de droits depuis Pexels API
 * - DALLE : Image générée par DALL-E (OpenAI)
 * - IMAGEN : Image générée par Imagen (Google)
 *
 * @example
 * ```php
 * $image = new Image();
 * $image->setSource(ImageSource::PEXELS);
 * $image->setSourceId('12345'); // ID Pexels
 *
 * if ($image->getSource()->requiresAttribution()) {
 *     echo $image->getAttribution();
 * }
 * ```
 */
enum ImageSource: string
{
    /**
     * Image uploadée directement par l'utilisateur.
     */
    case UPLOAD = 'upload';

    /**
     * Image depuis Pexels (stock photos gratuites).
     */
    case PEXELS = 'pexels';

    /**
     * Image générée par DALL-E (OpenAI).
     */
    case DALLE = 'dalle';

    /**
     * Image générée par Imagen (Google).
     */
    case IMAGEN = 'imagen';

    /**
     * Vérifie si la source nécessite une attribution.
     */
    public function requiresAttribution(): bool
    {
        return $this === self::PEXELS;
    }

    /**
     * Vérifie si la source est une IA générative.
     */
    public function isAiGenerated(): bool
    {
        return $this === self::DALLE || $this === self::IMAGEN;
    }

    /**
     * Vérifie si la source nécessite une clé API.
     */
    public function requiresApiKey(): bool
    {
        return $this !== self::UPLOAD;
    }

    /**
     * Retourne le libellé de la source.
     */
    public function label(): string
    {
        return match ($this) {
            self::UPLOAD => 'Upload',
            self::PEXELS => 'Pexels',
            self::DALLE => 'DALL-E',
            self::IMAGEN => 'Imagen',
        };
    }

    /**
     * Retourne l'icône associée à la source (pour l'UI).
     */
    public function icon(): string
    {
        return match ($this) {
            self::UPLOAD => '📤',
            self::PEXELS => '📷',
            self::DALLE => '🎨',
            self::IMAGEN => '🖼️',
        };
    }

    /**
     * Retourne le texte d'attribution par défaut.
     */
    public function defaultAttribution(): string
    {
        return match ($this) {
            self::UPLOAD => '',
            self::PEXELS => 'Photo from Pexels',
            self::DALLE => 'Generated by DALL-E',
            self::IMAGEN => 'Generated by Imagen',
        };
    }
}
